### ISSUE TITLE
the magic kingdom theme is not available 

### ISSUE THREAD

**Issue by xyychenchen** [LinkStackOrg/Magic-Kingdom#1]
### LinkStack version

4.8.0

### Description

when i open my page it shows "View [Magic-Kingdom-1.4.extra.custom-head] not found."
![image](https://github.com/user-attachments/assets/c6745781-6ba4-4e88-979c-6ffc16842e0f)
![image](https://github.com/user-attachments/assets/7e418d0d-a30a-44f5-8f10-30d7b0cf86ac)

### Details about your system

php8.1-fpm 
debian 12 

### How to reproduce

i uploade the theme to the theme folder and i choose the theme in the dashboard like before, and then the shows the page that the theme is not usable, the two default themes are ok, galaxy and poly sleek

**Comment by lastsamurai26** [comment]
This is not a problem with Linkstack itself, but a problem with the theme. 

Can you check if there is a folder called extra and inside is a file called custom-head.blade.php 
How did you upload the file?

**Comment by xyychenchen** [comment]
> This is not a problem with Linkstack itself, but a problem with the theme. 
> 
> Can you check if there is a folder called extra and inside is a file called custom-head.blade.php 
> How did you upload the file?

hey thank you for your response, and yes for your questions, I check the line that occurs errors,  the theme is right there and the parameters inside the themes config php is also true, customer theme parameter in the env file is also true, but it just said couldn't fins the theme, I also change the theme file permission to www-data and 755, not works

**Comment by lastsamurai26** [comment]
can you try the following command because i can't reproduce this issue 
tree /pahttoyourlinkstack/theme/

```
 tree  themes/MagicKingdom/

themes/MagicKingdom/
├── animations.css
├── brands.css
├── config.php
├── extra
│   ├── custom-assets
│   │   ├── karla-latin-400-normal.woff
│   │   ├── karla-latin-400-normal.woff2
│   │   ├── karla-latin-700-normal.woff
│   │   ├── karla-latin-700-normal.woff2
│   │   ├── karla-latin-ext-400-normal.woff
│   │   ├── karla-latin-ext-400-normal.woff2
│   │   ├── noto-sans-mono-cyrillic-400-normal.woff
│   │   ├── noto-sans-mono-cyrillic-400-normal.woff2
│   │   ├── noto-sans-mono-cyrillic-ext-400-normal.woff
│   │   ├── noto-sans-mono-cyrillic-ext-400-normal.woff2
│   │   ├── noto-sans-mono-greek-400-normal.woff
│   │   ├── noto-sans-mono-greek-400-normal.woff2
│   │   ├── noto-sans-mono-greek-ext-400-normal.woff
│   │   ├── noto-sans-mono-greek-ext-400-normal.woff2
│   │   ├── noto-sans-mono-latin-400-normal.woff
│   │   ├── noto-sans-mono-latin-400-normal.woff2
│   │   ├── noto-sans-mono-latin-ext-400-normal.woff
│   │   ├── noto-sans-mono-latin-ext-400-normal.woff2
│   │   ├── noto-sans-mono-vietnamese-400-normal.woff
│   │   └── noto-sans-mono-vietnamese-400-normal.woff2
│   └── custom-head.blade.php
├── Kingdom.jpeg
├── LICENSE
├── preview.png
├── readme.md
├── share.button.css
└── skeleton-auto.css

3 directories, 30 files
```

**Comment by xyychenchen** [comment]
> can you try the following command because i can't reproduce this issue tree /pahttoyourlinkstack/theme/
> 
> ```
>  tree  themes/MagicKingdom/
> 
> themes/MagicKingdom/
> ├── animations.css
> ├── brands.css
> ├── config.php
> ├── extra
> │   ├── custom-assets
> │   │   ├── karla-latin-400-normal.woff
> │   │   ├── karla-latin-400-normal.woff2
> │   │   ├── karla-latin-700-normal.woff
> │   │   ├── karla-latin-700-normal.woff2
> │   │   ├── karla-latin-ext-400-normal.woff
> │   │   ├── karla-latin-ext-400-normal.woff2
> │   │   ├── noto-sans-mono-cyrillic-400-normal.woff
> │   │   ├── noto-sans-mono-cyrillic-400-normal.woff2
> │   │   ├── noto-sans-mono-cyrillic-ext-400-normal.woff
> │   │   ├── noto-sans-mono-cyrillic-ext-400-normal.woff2
> │   │   ├── noto-sans-mono-greek-400-normal.woff
> │   │   ├── noto-sans-mono-greek-400-normal.woff2
> │   │   ├── noto-sans-mono-greek-ext-400-normal.woff
> │   │   ├── noto-sans-mono-greek-ext-400-normal.woff2
> │   │   ├── noto-sans-mono-latin-400-normal.woff
> │   │   ├── noto-sans-mono-latin-400-normal.woff2
> │   │   ├── noto-sans-mono-latin-ext-400-normal.woff
> │   │   ├── noto-sans-mono-latin-ext-400-normal.woff2
> │   │   ├── noto-sans-mono-vietnamese-400-normal.woff
> │   │   └── noto-sans-mono-vietnamese-400-normal.woff2
> │   └── custom-head.blade.php
> ├── Kingdom.jpeg
> ├── LICENSE
> ├── preview.png
> ├── readme.md
> ├── share.button.css
> └── skeleton-auto.css
> 
> 3 directories, 30 files
> ```

/var/www/html/linkstack/themes/Magic-Kingdom-1.4
├── Kingdom.jpeg
├── LICENSE
├── animations.css
├── brands.css
├── config.php
├── extra
│   ├── custom-assets
│   │   ├── karla-latin-400-normal.woff
│   │   ├── karla-latin-400-normal.woff2
│   │   ├── karla-latin-700-normal.woff
│   │   ├── karla-latin-700-normal.woff2
│   │   ├── karla-latin-ext-400-normal.woff
│   │   ├── karla-latin-ext-400-normal.woff2
│   │   ├── noto-sans-mono-cyrillic-400-normal.woff
│   │   ├── noto-sans-mono-cyrillic-400-normal.woff2
│   │   ├── noto-sans-mono-cyrillic-ext-400-normal.woff
│   │   ├── noto-sans-mono-cyrillic-ext-400-normal.woff2
│   │   ├── noto-sans-mono-greek-400-normal.woff
│   │   ├── noto-sans-mono-greek-400-normal.woff2
│   │   ├── noto-sans-mono-greek-ext-400-normal.woff
│   │   ├── noto-sans-mono-greek-ext-400-normal.woff2
│   │   ├── noto-sans-mono-latin-400-normal.woff
│   │   ├── noto-sans-mono-latin-400-normal.woff2
│   │   ├── noto-sans-mono-latin-ext-400-normal.woff
│   │   ├── noto-sans-mono-latin-ext-400-normal.woff2
│   │   ├── noto-sans-mono-vietnamese-400-normal.woff
│   │   └── noto-sans-mono-vietnamese-400-normal.woff2
│   └── custom-head.blade.php
├── preview.png
├── readme.md
├── share.button.css
└── skeleton-auto.css

2 directories, 30 files

**Comment by lastsamurai26** [comment]
I am really Sry ,but  I absolutely can't reproduce this problem. 
Can you delete the theme via FTP and then upload it via studio/theme ?

**Comment by xyychenchen** [comment]
> I am really Sry ,but I absolutely can't reproduce this problem. Can you delete the theme via FTP and then upload it via studio/theme ?

dear, you can check this https://github.com/LinkStackOrg/LinkStack/issues/819 , 

and for your question, i try to upload it through the dashboard but it keep said 413 Request Entity Too Large
nginx/1.18.0 (Ubuntu)

my nginx conf file for linkstack has this server configuratoin client_max_body_size 200m;
my php.ini has these two: post_max_size = 200M, upload_max_filesize = 200M 

and I just cannot upload through dashboard , can you please tell me how to fix this in order to upload through dashboard,
